name: Deploy to server via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 root@91.84.111.102 << 'EOF'
              if ! command -v docker &> /dev/null; then
                apt update
                apt install -y apt-transport-https ca-certificates curl software-properties-common
                curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
                add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
                apt update
                apt install -y docker-ce
              fi

              if [ ! -d "/root/telegram-bot" ]; then
                git clone https://github.com/niccneimi/bot-karpov.git /root/telegram-bot
              fi

              cd /root/telegram-bot
              git reset --hard
              git pull origin master
              docker build -t bot-karpov .
              docker run -d --name bot-karpov bot-karpov
            EOF
