name: Deploy to server via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 91.84.111.102 >> ~/.ssh/known_hosts

      - name: Check SSH key
        run: head -20 ~/.ssh/id_ed25519


      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@91.84.111.102 << 'EOF'
            if ! command -v docker &> /dev/null; then
              apt update
              apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
              echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
              apt update
              apt install -y docker-ce docker-ce-cli containerd.io
            fi

            if [ ! -d "/root/telegram-bot" ]; then
              git clone https://github.com/niccneimi/bot-karpov.git /root/telegram-bot
            fi

            cd /root/telegram-bot
            git reset --hard
            git pull origin master

            if [ "$(docker ps -q -f name=bot-karpov)" ]; then
              docker stop bot-karpov
              docker rm bot-karpov
            fi

            docker build -t bot-karpov .
            docker run -d --name bot-karpov bot-karpov
          EOF
